### ISSUE TITLE
First 3 inputs not working

### ISSUE THREAD

**Issue by GiselleMartinez006** [JeromeBlackwell/fsw-120#1]
Hi Jerome, 
I cloned your code and ran it on my end once again. I found out that this line is the reason why the value you enter in the inputs is not being saved. 
https://github.com/JeromeBlackwell/fsw-120/blob/2021e94cb40bf2f1c5e48f058dc41f8ed6073731/week4/project2-app/src/App.js#L20

In the last half where it says: 
`this.setState({ [value] :value}) ` 
it should be: 
this.setState({ [name] :value}) 
instead.

**Comment by JeromeBlackwell** [comment]
Thanks again

Yours truly,

Jerome R. Blackwell
